export const GLOBAL_SEARCH = "GLOBAL_SEARCH"
export const CLEAR_GLOBAL_SEARCH = "CLEAR_GLOBAL_SEARCH"
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SHOW_RESULTS = "SHOW_RESULTS";

// product actions
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const EDIT_ON = "EDIT_ON"
export const EDIT_OFF = "EDIT_OFF"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const LOAD_PRODUCTS = "LOAD_PRODUCTS"
export const LOW_STOCK = "LOW_STOCK"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"
export const BEST_SELLERS = "BEST_SELLERS";
export const TOP_PRODUCTS = "TOP_PRODUCTS";
export const REMOVE_FEATURED = "REMOVE_FEATURED";
export const ADD_FEATURED = "ADD_FEATURED";
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const CLEAR_SEARCH_PRODUCTS = "CLEAR_SEARCH_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const TOGGLE_FEATURED = "TOGGLE_FEATURED";
export const CLEAR_PRODUCTS_ERROR = "CLEAR_PRODUCTS_ERROR";



//orders action
export const PENDING_ORDERS = "PENDING_ORDERS"
export const RECENT_ORDERS = "RECENT_ORDERS"
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS"
export const GET_SINGLE_ORDER_FAIL = "GET_SINGLE_ORDER_FAIL";
export const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_START = "GET_ORDERS_START"
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR"
export const COMPLETED_ORDERS = "COMPLETED_ORDERS"
export const DELETE_ORDER_START = "DELETE_ORDER_START"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR"
export const CHANGE_STATUS_START = "CHANGE_STATUS_START"
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS"
export const CHANGE_STATUS_ERROR = "CHANGE_STATUS_ERROR"
export const SEARCH_ORDERS = "SEARCH_ORDERS"
export const CLEAR_SEARCH_ORDERS = "CLEAR_SEARCH_ORDERS"
export const CLEAR_ORDERS_ERROR = "CLEAR_ORDERS_ERROR";


// notification action
export const FETCH_NOTIFICATIONS_START = "FETCH_NOTIFICATIONS_START";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_ERROR = "FETCH_NOTIFICATIONS_ERROR";
export const FILTERED_NOTIFICATIONS = "FILTERED_NOTIFICATIONS";
export const MARK_AS_READ_START = "MARK_AS_READ_START";
export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_ERROR = "MARK_AS_READ_ERROR";
export const MARK_ALL_AS_READ_START = "MARK_ALL_AS_READ_START";
export const MARK_ALL_AS_READ_SUCCESS = "MARK_ALL_AS_READ_SUCCESS";
export const MARK_ALL_AS_READ_ERROR = "MARK_ALL_AS_READ_ERROR";
export const DELETE_NOTIFICATION_START = "DELETE_NOTIFICATION_START";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_ERROR = "DELETE_NOTIFICATION_ERROR";
export const UNREAD_COUNT = "UNREAD_COUNT";
export const CLEAR_READ_NOTIFICATIONS = "CLEAR_READ_NOTIFICATIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const CLEAR_NOTIFICATIONS_ERROR = "CLEAR_NOTIFICATIONS_ERROR";


//auth actions
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_LOADING = "SET_LOADING";