export const GLOBAL_SEARCH = "GLOBAL_SEARCH"
export const CLEAR_GLOBAL_SEARCH = "CLEAR_GLOBAL_SEARCH"
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SHOW_RESULTS = "SHOW_RESULTS";

// product actions
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const EDIT_ON = "EDIT_ON"
export const EDIT_OFF = "EDIT_OFF"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const LOAD_PRODUCTS = "LOAD_PRODUCTS"
export const LOW_STOCK = "LOW_STOCK"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"
export const BEST_SELLERS = "BEST_SELLERS";
export const TOP_PRODUCTS = "TOP_PRODUCTS";
export const REMOVE_FEATURED = "REMOVE_FEATURED";
export const ADD_FEATURED = "ADD_FEATURED";
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const CLEAR_SEARCH_PRODUCTS = "CLEAR_SEARCH_PRODUCTS";


//orders action
export const PENDING_ORDERS = "PENDING_ORDERS"
export const RECENT_ORDERS = "RECENT_ORDERS"
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const COMPLETED_ORDERS = "COMPLETED_ORDERS"
export const DELETE_ORDER = "DELETE_ORDER"
export const CHANGE_STATUS = "CHANGE_STATUS"
export const SEARCH_ORDERS = "SEARCH_ORDERS"
export const CLEAR_SEARCH_ORDERS = "CLEAR_SEARCH_ORDERS"


// notification action
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const FILTERED_NOTIFICATIONS = "FILTERED_NOTIFICATIONS";
export const MARK_AS_READ = "MARK_AS_READ";
export const MARK_ALL_AS_READ = "MARK_ALL_AS_READ";
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
export const UNREAD_COUNT = "UNREAD_COUNT";
export const CLEAR_READ_NOTIFICATIONS = "CLEAR_READ_NOTIFICATIONS";