import {
  Upload,
  Pen,
  Bell,
  ShoppingBag,
  PackagePlus,
  Star,
  Sparkles,
  Truck
} from "lucide-react";

export const sidebarLinks = [
  {
    title: "Dashboard",
    icon: <Star />,
    url: "/",
  },
  {
    title: "All Products",
    icon: <ShoppingBag />,
    url: "/products",
  },
  {
    title: "Add Product",
    icon: <PackagePlus />,
    url: "/add-product",
  },
  {
    title: "Orders",
    icon: <Truck />,
    url: "/orders",
  },
  {
    title: "New Arrival",
    icon: <Sparkles />,
    url: "/new-arrival",
  },
  {
    title: "Excel File Upload",
    icon: <Upload />,
    url: "/upload",
  },
  {
    title: "Notifications",
    icon: <Bell />,
    url: "/notifications",
  },
];

export const categories = [
  {
    category: "Women",
    subCategories: [
      "Clothes",
      "Shoes",
      "Clothing Accessories",
      "Clothing Materials",
    ],
  },
  {
    category: "Men",
    subCategories: [
      "Clothes",
      "Shoes",
      "Clothing Accessories",
      "Clothing Materials",
    ],
  },
  {
    category: "Teens & Kids",
    subCategories: ["Clothes", "Shoes", "Clothing Accessories", "Toys & Games"],
  },
  {
    category: "Babies",
    subCategories: ["Clothes", "Shoes", "Toys & Games", "Baby Products"],
  },
  {
    category: "Accessories",
    subCategories: [
      "Household Items",
      "Clothing Accessories",
      "Electronic Accessories",
    ],
  },
];

export const commonTags = [
  "casual",
  "formal",
  "party",
  "sports",
  "outdoor",
  "indoor",
  "travel",
  "beach",
  "summer",
  "spring",
  "sneakers",
  "boots",
  "heels",
  "jeans",
  "shirts",
  "dresses",
  "sandals",
  "running",
  "leather",
  "cotton",
  "hoodie",
  "suit",
  "jacket",
  "sweater",
  "shorts",
  "t-shirt",
  "pajamas",
  "loungewear",
  "underwear",
  "accessories",
  "bags",
  "belts",
  "jewelry",
];

export const tableDetails = [
  "product",
  "productID",
  "category",
  "price",
  "sales",
  "stock",
  "action",
];
export const ordersDetails = [
  "product",
  "customer",
  "order ID",
  "price",
  "quantity",
  "payment",
  "status",
  "action",
];

export const lowStockTable = [
  "product",
  "productID",
  "category",
  "stock",
  "action",
];

export const recentOrdersTable = [
  "product",
  "customer",
  "order ID",
  "quantity",
  "price",
  "status",
];
export const globalOrdersTable = [
  "product",
  "customer",
  "order ID",
  "status",
  "action",
];

export const featuredTable = [
  "product",
  "productID",
  "category",
  "visits",
  "action",
];
export const bestSellersTable = [
  "product",
  "productID",
  "price",
  "sales",
];
export const topProductsTable = [
  "product",
  "productID",
  "price",
  "visits",
];

export const productOverviewTable = [
  "product",
  "productID",
  "price",
  "stock",
  "sales",
  "visits"
]
export const globalProductsTable = [
  "product",
  "productID",
  "price",
  "stock",
  "action",
]

export const sampleNotifications = [
  {
    id: 1,
    title: "New Order Received",
    message: "Order #12345 has been placed for $129.99",
    time: "5 minutes ago",
    isRead: false,
    type: "order",
    priority: "high",
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 2,
    title: "Payment Processed",
    message: "Payment for order #12340 has been successfully processed",
    time: "30 minutes ago",
    isRead: true,
    type: "payment",
    priority: "medium",
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 3,
    title: "Product Out of Stock",
    message: "Nike Air Max 95 is now out of stock",
    time: "1 hour ago",
    isRead: false,
    type: "inventory",
    priority: "high",
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 4,
    title: "New User Registration",
    message: "John Doe has created a new account",
    time: "2 hours ago",
    isRead: false,
    type: "user",
    priority: "low",
    timestamp: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
  },
  {
    id: 5,
    title: "System Update Complete",
    message: "The system has been updated to version 2.3.0",
    time: "5 hours ago",
    isRead: false,
    type: "system",
    priority: "medium",
    timestamp: new Date(Date.now() - 5 * 60 * 60000).toISOString(),
  },
  {
    id: 6,
    title: "Product Return Request",
    message: "Customer requested return for order #12288",
    time: "1 day ago",
    isRead: true,
    type: "order",
    priority: "medium",
    timestamp: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
  },
  {
    id: 7,
    title: "Weekly Report Generated",
    message: "Sales report for last week is now available",
    time: "2 days ago",
    isRead: true,
    type: "report",
    priority: "low",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: 8,
    title: "New Order Received",
    message: "Order #12345 has been placed for $129.99",
    time: "5 minutes ago",
    isRead: true,
    type: "order",
    priority: "high",
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 9,
    title: "Payment Processed",
    message: "Payment for order #12340 has been successfully processed",
    time: "30 minutes ago",
    isRead: false,
    type: "payment",
    priority: "medium",
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 10,
    title: "Product Out of Stock",
    message: "Nike Air Max 95 is now out of stock",
    time: "1 hour ago",
    isRead: true,
    type: "inventory",
    priority: "high",
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 11,
    title: "New User Registration",
    message: "John Doe has created a new account",
    time: "2 hours ago",
    isRead: true,
    type: "user",
    priority: "low",
    timestamp: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
  },
  {
    id: 12,
    title: "System Update Complete",
    message: "The system has been updated to version 2.3.0",
    time: "5 hours ago",
    isRead: false,
    type: "system",
    priority: "medium",
    timestamp: new Date(Date.now() - 5 * 60 * 60000).toISOString(),
  },
  {
    id: 13,
    title: "Product Return Request",
    message: "Customer requested return for order #12288",
    time: "1 day ago",
    isRead: true,
    type: "order",
    priority: "medium",
    timestamp: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
  },
  {
    id: 14,
    title: "Weekly Report Generated",
    message: "Sales report for last week is now available",
    time: "2 days ago",
    isRead: true,
    type: "report",
    priority: "low",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60000).toISOString(),
  },
];

export const sampleOrderData = [
  {
    orderId: "ORD192847",
    customerId: "CUST2672",
    customerName: "Emma Thompson",
    productName: "Taste of the Wild Formula Finder",
    productId: "PRD67821",
    price: 50.47,
    quantity: 1,
    status: "Delivered",
    orderDate: "2023-11-18",
    shippingAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
    subtotal: 50.47,
    shipping: 10.0,
    tax: 5.0,
    total: 65.47,
  },
  {
    orderId: "ORD192148",
    customerId: "CUST2673",
    customerName: "James Wilson",
    productName: "Proden Plaqueoff Dental Bites Dog, 150 G",
    productId: "PRD67822",
    price: 28672.36,
    quantity: 2,
    status: "Pending",
    orderDate: "2023-11-21",
    shippingAddress: "4517 Washington Ave. Manchester, Kentucky 39495",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
    subtotal: 57344.72,
    shipping: 15.0,
    tax: 5730.47,
    total: 63090.19,
  },
  {
    orderId: "ORD192849",
    customerId: "CUST2674",
    customerName: "Sophia Rodriguez",
    productName: "Zuke's Lil' Links Healthy Little Sausage Links",
    productId: "PRD67823",
    price: 1452.5,
    quantity: 1,
    status: "Processing",
    orderDate: "2023-11-12",
    shippingAddress: "2464 Royal Ln. Mesa, New Jersey 45463",
    paymentMethod: "PayPal",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
    subtotal: 1452.5,
    shipping: 12.0,
    tax: 145.25,
    total: 1609.75,
  },
  {
    orderId: "ORD192850",
    customerId: "CUST2675",
    customerName: "William Brown",
    productName: "Rachael Ray Nutrish Grain Free Chicken Drumstick",
    productId: "PRD67824",
    price: 28672.36,
    quantity: 3,
    status: "Delivered",
    orderDate: "2023-11-25",
    shippingAddress: "8502 Preston Rd. Inglewood, Maine 98380",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    subtotal: 86017.08,
    shipping: 20.0,
    tax: 8601.71,
    total: 94638.79,
  },
  {
    orderId: "ORD192851",
    customerId: "CUST2676",
    customerName: "Oliver Davis",
    productName: "Fruitables Dog Treats Sweet Potato & Pecan Flavor",
    productId: "PRD67825",
    price: 1452.5,
    quantity: 2,
    status: "Shipped",
    orderDate: "2023-12-24",
    shippingAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    subtotal: 2905.0,
    shipping: 15.0,
    tax: 290.5,
    total: 3210.5,
  },
  {
    orderId: "ORD192852",
    customerId: "CUST2677",
    customerName: "Isabella Martinez",
    productName: "Taste of the Wild Formula Finder",
    productId: "PRD67826",
    price: 50.47,
    quantity: 4,
    status: "Delivered",
    orderDate: "2023-11-5",
    shippingAddress: "4140 Parker Rd. Allentown, New Mexico 31134",
    paymentMethod: "PayPal",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
    subtotal: 201.88,
    shipping: 10.0,
    tax: 20.19,
    total: 232.07,
  },
  {
    orderId: "ORD192853",
    customerId: "CUST2678",
    customerName: "Ethan Taylor",
    productName: "Proden Plaqueoff Dental Bites Dog, 150 G",
    productId: "PRD67827",
    price: 28672.36,
    quantity: 1,
    status: "Processing",
    orderDate: "2023-12-26",
    shippingAddress: "2715 Ash Dr. San Jose, South Dakota 83475",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
    subtotal: 28672.36,
    shipping: 15.0,
    tax: 2867.24,
    total: 31554.6,
  },
  {
    orderId: "ORD192854",
    customerId: "CUST2679",
    customerName: "Ava Anderson",
    productName: "Zuke's Lil' Links Healthy Little Sausage Links",
    productId: "PRD67828",
    price: 1452.5,
    quantity: 2,
    status: "Pending",
    orderDate: "2023-11-7",
    shippingAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
    subtotal: 2905.0,
    shipping: 12.0,
    tax: 290.5,
    total: 3207.5,
  },
  {
    orderId: "ORD193847",
    customerId: "CUST2672",
    customerName: "Emma Thompson",
    productName: "Taste of the Wild Formula Finder",
    productId: "PRD67821",
    price: 50.47,
    quantity: 1,
    status: "Delivered",
    orderDate: "2023-11-25",
    shippingAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
    subtotal: 50.47,
    shipping: 10.0,
    tax: 5.0,
    total: 65.47,
  },
  {
    orderId: "ORD192248",
    customerId: "CUST2673",
    customerName: "James Wilson",
    productName: "Proden Plaqueoff Dental Bites Dog, 150 G",
    productId: "PRD67822",
    price: 28672.36,
    quantity: 2,
    status: "Pending",
    orderDate: "2023-12-24",
    shippingAddress: "4517 Washington Ave. Manchester, Kentucky 39495",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
    subtotal: 57344.72,
    shipping: 15.0,
    tax: 5730.47,
    total: 63090.19,
  },
  {
    orderId: "ORD192899",
    customerId: "CUST2674",
    customerName: "Sophia Rodriguez",
    productName: "Zuke's Lil' Links Healthy Little Sausage Links",
    productId: "PRD67823",
    price: 1452.5,
    quantity: 1,
    status: "Processing",
    orderDate: "2023-11-2",
    shippingAddress: "2464 Royal Ln. Mesa, New Jersey 45463",
    paymentMethod: "PayPal",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
    subtotal: 1452.5,
    shipping: 12.0,
    tax: 145.25,
    total: 1609.75,
  },
  {
    orderId: "ORD492850",
    customerId: "CUST2675",
    customerName: "William Brown",
    productName: "Rachael Ray Nutrish Grain Free Chicken Drumstick",
    productId: "PRD67824",
    price: 28672.36,
    quantity: 3,
    status: "Delivered",
    orderDate: "2023-12-3",
    shippingAddress: "8502 Preston Rd. Inglewood, Maine 98380",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    subtotal: 86017.08,
    shipping: 20.0,
    tax: 8601.71,
    total: 94638.79,
  },
  {
    orderId: "ORD192651",
    customerId: "CUST2676",
    customerName: "Oliver Davis",
    productName: "Fruitables Dog Treats Sweet Potato & Pecan Flavor",
    productId: "PRD67825",
    price: 1452.5,
    quantity: 2,
    status: "Shipped",
    orderDate: "2023-11-21",
    shippingAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    subtotal: 2905.0,
    shipping: 15.0,
    tax: 290.5,
    total: 3210.5,
  },
  {
    orderId: "ORD142852",
    customerId: "CUST2677",
    customerName: "Isabella Martinez",
    productName: "Taste of the Wild Formula Finder",
    productId: "PRD67826",
    price: 50.47,
    quantity: 4,
    status: "Delivered",
    orderDate: "2023-12-5",
    shippingAddress: "4140 Parker Rd. Allentown, New Mexico 31134",
    paymentMethod: "PayPal",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
    subtotal: 201.88,
    shipping: 10.0,
    tax: 20.19,
    total: 232.07,
  },
  {
    orderId: "ORD194851",
    customerId: "CUST2678",
    customerName: "Ethan Taylor",
    productName: "Proden Plaqueoff Dental Bites Dog, 150 G",
    productId: "PRD67827",
    price: 28672.36,
    quantity: 1,
    status: "Processing",
    orderDate: "2023-11-29",
    shippingAddress: "2715 Ash Dr. San Jose, South Dakota 83475",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
    subtotal: 28672.36,
    shipping: 15.0,
    tax: 2867.24,
    total: 31554.6,
  },
  {
    orderId: "ORD192954",
    customerId: "CUST2679",
    customerName: "Ava Anderson",
    productName: "Zuke's Lil' Links Healthy Little Sausage Links",
    productId: "PRD67828",
    price: 1452.5,
    quantity: 2,
    status: "Pending",
    orderDate: "2023-12-1",
    shippingAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
    subtotal: 2905.0,
    shipping: 12.0,
    tax: 290.5,
    total: 3207.5,
  },
  {
    orderId: "ORD194847",
    customerId: "CUST2672",
    customerName: "Emma Thompson",
    productName: "Taste of the Wild Formula Finder",
    productId: "PRD67821",
    price: 50.47,
    quantity: 1,
    status: "Delivered",
    orderDate: "2023-11-20",
    shippingAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
    subtotal: 50.47,
    shipping: 10.0,
    tax: 5.0,
    total: 65.47,
  },
  {
    orderId: "ORD152848",
    customerId: "CUST2673",
    customerName: "James Wilson",
    productName: "Proden Plaqueoff Dental Bites Dog, 150 G",
    productId: "PRD67822",
    price: 28672.36,
    quantity: 2,
    status: "Pending",
    orderDate: "2023-11-11",
    shippingAddress: "4517 Washington Ave. Manchester, Kentucky 39495",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
    subtotal: 57344.72,
    shipping: 15.0,
    tax: 5730.47,
    total: 63090.19,
  },
  {
    orderId: "ORD192869",
    customerId: "CUST2674",
    customerName: "Sophia Rodriguez",
    productName: "Zuke's Lil' Links Healthy Little Sausage Links",
    productId: "PRD67823",
    price: 1452.5,
    quantity: 1,
    status: "Processing",
    orderDate: "2023-12-25",
    shippingAddress: "2464 Royal Ln. Mesa, New Jersey 45463",
    paymentMethod: "PayPal",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
    subtotal: 1452.5,
    shipping: 12.0,
    tax: 145.25,
    total: 1609.75,
  },
  {
    orderId: "ORD192750",
    customerId: "CUST2675",
    customerName: "William Brown",
    productName: "Rachael Ray Nutrish Grain Free Chicken Drumstick",
    productId: "PRD67824",
    price: 28672.36,
    quantity: 3,
    status: "Delivered",
    orderDate: "2023-11-23",
    shippingAddress: "8502 Preston Rd. Inglewood, Maine 98380",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    subtotal: 86017.08,
    shipping: 20.0,
    tax: 8601.71,
    total: 94638.79,
  },
  {
    orderId: "ORD292851",
    customerId: "CUST2676",
    customerName: "Oliver Davis",
    productName: "Fruitables Dog Treats Sweet Potato & Pecan Flavor",
    productId: "PRD67825",
    price: 1452.5,
    quantity: 2,
    status: "Shipped",
    orderDate: "2023-12-24",
    shippingAddress: "1901 Thornridge Cir. Shiloh, Hawaii 81063",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    subtotal: 2905.0,
    shipping: 15.0,
    tax: 290.5,
    total: 3210.5,
  },
  {
    orderId: "ORD192552",
    customerId: "CUST2677",
    customerName: "Isabella Martinez",
    productName: "Taste of the Wild Formula Finder",
    productId: "PRD67826",
    price: 50.47,
    quantity: 4,
    status: "Delivered",
    orderDate: "2023-11-25",
    shippingAddress: "4140 Parker Rd. Allentown, New Mexico 31134",
    paymentMethod: "PayPal",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
    subtotal: 201.88,
    shipping: 10.0,
    tax: 20.19,
    total: 232.07,
  },
  {
    orderId: "ORD192883",
    customerId: "CUST2678",
    customerName: "Ethan Taylor",
    productName: "Proden Plaqueoff Dental Bites Dog, 150 G",
    productId: "PRD67827",
    price: 28672.36,
    quantity: 1,
    status: "Processing",
    orderDate: "2023-11-25",
    shippingAddress: "2715 Ash Dr. San Jose, South Dakota 83475",
    paymentMethod: "Credit Card",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
    subtotal: 28672.36,
    shipping: 15.0,
    tax: 2867.24,
    total: 31554.6,
  },
  {
    orderId: "ORD192894",
    customerId: "CUST2679",
    customerName: "Ava Anderson",
    productName: "Zuke's Lil' Links Healthy Little Sausage Links",
    productId: "PRD67828",
    price: 1452.5,
    quantity: 2,
    status: "Pending",
    orderDate: "2023-11-22",
    shippingAddress: "3517 W. Gray St. Utica, Pennsylvania 57867",
    paymentMethod: "Cash on Delivery (COD)",
    image:
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
    subtotal: 2905.0,
    shipping: 12.0,
    tax: 290.5,
    total: 3207.5,
  },
];

export const productsDetails = [
  {
    id: 1,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "28",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "22",
    visits: "234",
  },
  {
    id: 2,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "1",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "31",
    visits: "134",
  },
  {
    id: 3,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "8",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "2",
    visits: "34",
  },
  {
    id: 4,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "18",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "52",
    visits: "434",
  },
  {
    id: 5,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "22",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "21",
    visits: "256",
  },
  {
    id: 6,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "5",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "12",
    visits: "434",
  },
  {
    id: 7,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "0",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "51",
    visits: "2234",
  },
  {
    id: 8,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "0",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "22",
    visits: "576",
  },
  {
    id: 9,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "3",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "44",
    visits: "34",
  },
  {
    id: 10,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "7",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "29",
    visits: "1234",
  },
  {
    id: 11,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "0",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "220",
    visits: "23467",
  },
  {
    id: 12,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "28",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "21",
    visits: "334",
  },
  {
    id: 13,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "99",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "242",
    visits: "24",
  },
  {
    id: 14,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "28",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "220",
    visits: "23894",
  },
  {
    id: 15,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "8",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "228",
    visits: "2334",
  },
  {
    id: 16,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "14",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "122",
    visits: "274",
  },
  {
    id: 17,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "28",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "2112",
    visits: "23234",
  },
  {
    id: 18,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "99",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "902",
    visits: "23564",
  },
  {
    id: 19,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "28",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "459",
    visits: "23478",
  },
  {
    id: 20,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: null,
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "8",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "2222",
    visits: "34234",
  },
  {
    id: 21,
    brand: "Jumia",
    category: "Men",
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    // featured: true,
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    name: "Mens Loafers",
    price: "7900",
    sizes: [
      { form: "size-letters", value: "xl", stock: "23", price: "19000" },
      { form: "size-letters", value: "m", stock: "25", price: "16000" },
      { form: "size-letters", value: "l", stock: "15", price: "17000" },
    ],
    specifications: { color: "grey", Size: "40ml", material: "glass" },
    stock: "14",
    subCategory: "Shoes",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    sales: "2290",
    visits: "12364",
  },
];
