export const products = [
  {
    _id: "6859bfd5fedc382b241bf397",
    productId: "2",
    name: "Floral Summer Dress",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Women",
    subCategory: "Clothes",
    price: 12500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 1,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf398",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf399",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf39a",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user101",
        reviewTitle: "Reliable",
        reviewMessage: "Fast delivery and great quality. Will buy again!",
        rating: 5,
        date: "2025-01-05T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf39b",
      },
      {
        userName: "user102",
        reviewTitle: "Reliable",
        reviewMessage: "Good product but packaging was a bit damaged.",
        rating: 4,
        date: "2025-01-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf39c",
      },
      {
        userName: "user104",
        reviewTitle: "Reliable",
        reviewMessage: "Exactly as described. Highly recommended.",
        rating: 5,
        date: "2025-01-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf39d",
      },
    ],
    featured: false,
    sales: 31,
    visits: 134,
    rating: {
      average: 4.5,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.237Z",
    updatedAt: "2025-07-01T21:19:34.733Z",
  },
  {
    _id: "6859bfd5fedc382b241bf39e",
    productId: "3",
    name: "Leather Handbag",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Accessories",
    subCategory: "Clothing Accessories",
    price: 18500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: [
      "summer",
      "formal",
      "party",
      "spring",
      "sports",
      "sneakers",
      "running",
      "leather",
    ],
    brand: "Jumia",
    stock: 8,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user104",
        reviewTitle: "Reliable",
        reviewMessage: "Exactly as described. Highly recommended.",
        rating: 5,
        date: "2025-01-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf39f",
      },
    ],
    featured: true,
    sales: 2,
    visits: 34,
    rating: {
      average: 5,
      reviewsCount: 1,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.237Z",
    updatedAt: "2025-06-29T23:17:53.034Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3b6",
    productId: "7",
    name: "Leather Belt",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Men",
    subCategory: "Clothing Accessories",
    price: 3200,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 0,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "oser107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3b7",
      },
      {
        userName: "user108",
        reviewTitle: "Reliable",
        reviewMessage: "Came late, but good quality.",
        rating: 4,
        date: "2025-01-28T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3b8",
      },
      {
        userName: "user110",
        reviewTitle: "Reliable",
        reviewMessage: "Does what it says. Happy with it.",
        rating: 4,
        date: "2025-02-03T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3b9",
      },
      {
        userName: "user111",
        reviewTitle: "Reliable",
        reviewMessage: "Perfect condition and well-packaged.",
        rating: 5,
        date: "2025-02-06T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ba",
      },
    ],
    featured: false,
    sales: 51,
    visits: 2234,
    rating: {
      average: 4.5,
      reviewsCount: 4,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-07-01T21:14:45.117Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3c0",
    productId: "9",
    name: "Baby Lotion",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Babies",
    subCategory: "Baby Products",
    price: 2500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 3,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user112",
        reviewTitle: "Reliable",
        reviewMessage: "Not worth the price.",
        rating: 2,
        date: "2025-02-08T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3c1",
      },
      {
        userName: "user113",
        reviewTitle: "Reliable",
        reviewMessage: "Met my expectations completely.",
        rating: 4,
        date: "2025-02-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3c2",
      },
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3c3",
      },
    ],
    featured: true,
    sales: 44,
    visits: 34,
    rating: {
      average: 3,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3a0",
    productId: "4",
    name: "Classic White Shirt",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Men",
    subCategory: "Clothes",
    price: 6500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 18,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3a1",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3a2",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3a3",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user104",
        reviewTitle: "Reliable",
        reviewMessage: "Exactly as described. Highly recommended.",
        rating: 5,
        date: "2025-01-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3a4",
      },
      {
        userName: "user105",
        reviewTitle: "Reliable",
        reviewMessage: "Average quality. Gets the job done.",
        rating: 3,
        date: "2025-01-18T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3a5",
      },
      {
        userName: "user106",
        reviewTitle: "Reliable",
        reviewMessage: "Item didn’t match the description.",
        rating: 2,
        date: "2025-01-20T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3a6",
      },
      {
        userName: "user107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3a7",
      },
      {
        userName: "user108",
        reviewTitle: "Reliable",
        reviewMessage: "Came late, but good quality.",
        rating: 4,
        date: "2025-01-28T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3a8",
      },
    ],
    featured: false,
    sales: 52,
    visits: 434,
    rating: {
      average: 3,
      reviewsCount: 5,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.237Z",
    updatedAt: "2025-07-01T20:37:30.311Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3af",
    productId: "6",
    name: "Building Blocks Set",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Teens & Kids",
    subCategory: "Toys & Games",
    price: 3500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 5,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3b0",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3b1",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3b2",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3b3",
      },
      {
        userName: "user108",
        reviewTitle: "Reliable",
        reviewMessage: "Came late, but good quality.",
        rating: 4,
        date: "2025-01-28T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3b4",
      },
      {
        userName: "user110",
        reviewTitle: "Reliable",
        reviewMessage: "Does what it says. Happy with it.",
        rating: 4,
        date: "2025-02-03T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3b5",
      },
    ],
    featured: true,
    sales: 12,
    visits: 434,
    rating: {
      average: 4.5,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.237Z",
    updatedAt: "2025-07-01T21:16:07.635Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3cc",
    productId: "11",
    name: "Running Sneakers",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Men",
    subCategory: "Shoes",
    price: 11000,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 0,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user112",
        reviewTitle: "Reliable",
        reviewMessage: "Not worth the price.",
        rating: 2,
        date: "2025-02-08T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3cd",
      },
      {
        userName: "user113",
        reviewTitle: "Reliable",
        reviewMessage: "Met my expectations completely.",
        rating: 4,
        date: "2025-02-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ce",
      },
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3cf",
      },
      {
        userName: "user115",
        reviewTitle: "Reliable",
        reviewMessage: "Fantastic! Would recommend to friends.",
        rating: 5,
        date: "2025-02-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3d0",
      },
      {
        userName: "user109",
        reviewTitle: "Reliable",
        reviewMessage: "Terrible experience. Wouldn’t recommend.",
        rating: 1,
        date: "2025-02-01T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3d1",
      },
    ],
    featured: true,
    sales: 220,
    visits: 23467,
    rating: {
      average: 2.5,
      reviewsCount: 5,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3d2",
    productId: "12",
    name: "Denim Jacket",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Women",
    subCategory: "Clothes",
    price: 14500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 28,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3d3",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3d4",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3d5",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3d6",
      },
      {
        userName: "user115",
        reviewTitle: "Reliable",
        reviewMessage: "Fantastic! Would recommend to friends.",
        rating: 5,
        date: "2025-02-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3d7",
      },
      {
        userName: "user109",
        reviewTitle: "Reliable",
        reviewMessage: "Terrible experience. Wouldn’t recommend.",
        rating: 1,
        date: "2025-02-01T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3d8",
      },
    ],
    featured: null,
    sales: 21,
    visits: 334,
    rating: {
      average: 3,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3d9",
    productId: "13",
    name: "Kids Sandals",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    ],
    category: "Teens & Kids",
    subCategory: "Shoes",
    price: 4200,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 99,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user101",
        reviewTitle: "Reliable",
        reviewMessage: "Fast delivery and great quality. Will buy again!",
        rating: 5,
        date: "2025-01-05T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3da",
      },
      {
        userName: "user102",
        reviewTitle: "Reliable",
        reviewMessage: "Good product but packaging was a bit damaged.",
        rating: 4,
        date: "2025-01-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3db",
      },
      {
        userName: "user103",
        reviewTitle: "Reliable",
        reviewMessage: "Not satisfied. Item arrived faulty.",
        rating: 2,
        date: "2025-01-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3dc",
      },
    ],
    featured: true,
    sales: 242,
    visits: 24,
    rating: {
      average: 3.5,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3dd",
    productId: "14",
    name: "Ceramic Vase",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Accessories",
    subCategory: "Household Items",
    price: 6000,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 28,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3de",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3df",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3e0",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user104",
        reviewTitle: "Reliable",
        reviewMessage: "Exactly as described. Highly recommended.",
        rating: 5,
        date: "2025-01-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3e1",
      },
      {
        userName: "user105",
        reviewTitle: "Reliable",
        reviewMessage: "Average quality. Gets the job done.",
        rating: 3,
        date: "2025-01-18T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3e2",
      },
      {
        userName: "user106",
        reviewTitle: "Reliable",
        reviewMessage: "Item didn’t match the description.",
        rating: 2,
        date: "2025-01-20T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3e3",
      },
    ],
    featured: null,
    sales: 220,
    visits: 23894,
    rating: {
      average: 3.5,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3e4",
    productId: "15",
    name: "Casual Polo Shirt",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Men",
    subCategory: "Clothes",
    price: 7200,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 8,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3e5",
      },
      {
        userName: "user108",
        reviewTitle: "Reliable",
        reviewMessage: "Came late, but good quality.",
        rating: 4,
        date: "2025-01-28T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3e6",
      },
      {
        userName: "user109",
        reviewTitle: "Reliable",
        reviewMessage: "Terrible experience. Wouldn’t recommend.",
        rating: 1,
        date: "2025-02-01T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3e7",
      },
    ],
    featured: true,
    sales: 228,
    visits: 2334,
    rating: {
      average: 3.5,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3e8",
    productId: "16",
    name: "Silk Fabric",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Women",
    subCategory: "Clothing Materials",
    price: 9500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 14,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3e9",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3ea",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3eb",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user110",
        reviewTitle: "Reliable",
        reviewMessage: "Does what it says. Happy with it.",
        rating: 4,
        date: "2025-02-03T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ec",
      },
      {
        userName: "user111",
        reviewTitle: "Reliable",
        reviewMessage: "Perfect condition and well-packaged.",
        rating: 5,
        date: "2025-02-06T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ed",
      },
      {
        userName: "user112",
        reviewTitle: "Reliable",
        reviewMessage: "Not worth the price.",
        rating: 2,
        date: "2025-02-08T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ee",
      },
    ],
    featured: null,
    sales: 122,
    visits: 274,
    rating: {
      average: 4,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.239Z",
    updatedAt: "2025-06-23T20:57:57.239Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3ef",
    productId: "17",
    name: "Baby Booties",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    ],
    category: "Babies",
    subCategory: "Shoes",
    price: 2800,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 28,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3f0",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3f1",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3f2",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user113",
        reviewTitle: "Reliable",
        reviewMessage: "Met my expectations completely.",
        rating: 4,
        date: "2025-02-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3f3",
      },
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3f4",
      },
      {
        userName: "user115",
        reviewTitle: "Reliable",
        reviewMessage: "Fantastic! Would recommend to friends.",
        rating: 5,
        date: "2025-02-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3f5",
      },
    ],
    featured: null,
    sales: 2112,
    visits: 23234,
    rating: {
      average: 4,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.239Z",
    updatedAt: "2025-06-23T20:57:57.239Z",
  },
  {
    _id: "6859bfd5fedc382b241bf403",
    productId: "20",
    name: "Cotton Fabric",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    ],
    category: "Men",
    subCategory: "Clothing Materials",
    price: 5400,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 8,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user111",
        reviewTitle: "Reliable",
        reviewMessage: "Perfect condition and well-packaged.",
        rating: 5,
        date: "2025-02-06T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf404",
      },
    ],
    featured: null,
    sales: 2222,
    visits: 34234,
    rating: {
      average: 5,
      reviewsCount: 1,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.239Z",
    updatedAt: "2025-06-23T20:57:57.239Z",
  },
  {
    _id: "6859bfd5fedc382b241bf394",
    productId: "1",
    name: "Mens Loafers",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Men",
    subCategory: "Shoes",
    price: 9900,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: [
      "summer",
      "formal",
      "party",
      "spring",
      "sports",
      "sneakers",
      "running",
      "t-shirt",
    ],
    brand: "Jumia",
    stock: 12,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user101",
        reviewTitle: "Reliable",
        reviewMessage: "Fast delivery and great quality. Will buy again!",
        rating: 5,
        date: "2025-01-05T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf395",
      },
      {
        userName: "user102",
        reviewTitle: "Reliable",
        reviewMessage: "Good product but packaging was a bit damaged.",
        rating: 4,
        date: "2025-01-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf396",
      },
    ],
    featured: true,
    sales: 22,
    visits: 234,
    rating: {
      average: 4.5,
      reviewsCount: 2,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.236Z",
    updatedAt: "2025-06-29T23:12:10.064Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3a9",
    productId: "5",
    name: "Ladies Heels",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
    ],
    category: "Women",
    subCategory: "Shoes",
    price: 9900,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 22,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user104",
        reviewTitle: "Reliable",
        reviewMessage: "Exactly as described. Highly recommended.",
        rating: 5,
        date: "2025-01-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3aa",
      },
      {
        userName: "user106",
        reviewTitle: "Reliable",
        reviewMessage: "Item didn’t match the description.",
        rating: 2,
        date: "2025-01-20T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ab",
      },
      {
        userName: "user107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ac",
      },
      {
        userName: "user108",
        reviewTitle: "Reliable",
        reviewMessage: "Came late, but good quality.",
        rating: 4,
        date: "2025-01-28T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ad",
      },
      {
        userName: "user110",
        reviewTitle: "Reliable",
        reviewMessage: "Does what it says. Happy with it.",
        rating: 4,
        date: "2025-02-03T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ae",
      },
    ],
    featured: true,
    sales: 21,
    visits: 256,
    rating: {
      average: 4,
      reviewsCount: 5,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.237Z",
    updatedAt: "2025-06-29T23:23:09.447Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3bb",
    productId: "8",
    name: "Pearl Necklace",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Women",
    subCategory: "Clothing Accessories",
    price: 21000,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 0,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3bc",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3bd",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3be",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3bf",
      },
    ],
    featured: null,
    sales: 22,
    visits: 576,
    rating: {
      average: 5,
      reviewsCount: 1,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3fc",
    productId: "19",
    name: "Gold Plated Bracelet",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Accessories",
    subCategory: "Clothing Accessories",
    price: 15800,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 28,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3fd",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3fe",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3ff",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf400",
      },
      {
        userName: "user115",
        reviewTitle: "Reliable",
        reviewMessage: "Fantastic! Would recommend to friends.",
        rating: 5,
        date: "2025-02-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf401",
      },
      {
        userName: "user111",
        reviewTitle: "Reliable",
        reviewMessage: "Perfect condition and well-packaged.",
        rating: 5,
        date: "2025-02-06T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf402",
      },
    ],
    featured: null,
    sales: 459,
    visits: 23478,
    rating: {
      average: 4,
      reviewsCount: 3,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.239Z",
    updatedAt: "2025-06-23T20:57:57.239Z",
  },
  {
    _id: "6859bfd5fedc382b241bf405",
    productId: "21",
    name: "Mini Backpack",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Women",
    subCategory: "Clothing Accessories",
    price: 8700,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 14,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf406",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf407",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf408",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user107",
        reviewTitle: "Reliable",
        reviewMessage: "Awesome service and product. Loved it!",
        rating: 5,
        date: "2025-01-25T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf409",
      },
    ],
    featured: null,
    sales: 2290,
    visits: 12364,
    rating: {
      average: 5,
      reviewsCount: 1,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.239Z",
    updatedAt: "2025-06-23T20:57:57.239Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3c4",
    productId: "10",
    name: "Wireless Earbuds",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Accessories",
    subCategory: "Electronic Accessories",
    price: 17500,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 7,
    sizes: [
      {
        form: "size-letters",
        value: "xl",
        stock: 23,
        price: 19000,
        _id: "6859bfd5fedc382b241bf3c5",
      },
      {
        form: "size-letters",
        value: "m",
        stock: 25,
        price: 16000,
        _id: "6859bfd5fedc382b241bf3c6",
      },
      {
        form: "size-letters",
        value: "l",
        stock: 15,
        price: 17000,
        _id: "6859bfd5fedc382b241bf3c7",
      },
    ],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user112",
        reviewTitle: "Reliable",
        reviewMessage: "Not worth the price.",
        rating: 2,
        date: "2025-02-08T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3c8",
      },
      {
        userName: "user113",
        reviewTitle: "Reliable",
        reviewMessage: "Met my expectations completely.",
        rating: 4,
        date: "2025-02-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3c9",
      },
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3ca",
      },
      {
        userName: "user115",
        reviewTitle: "Reliable",
        reviewMessage: "Fantastic! Would recommend to friends.",
        rating: 5,
        date: "2025-02-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3cb",
      },
    ],
    featured: true,
    sales: 29,
    visits: 1234,
    rating: {
      average: 3.5,
      reviewsCount: 4,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.238Z",
    updatedAt: "2025-06-23T20:57:57.238Z",
  },
  {
    _id: "6859bfd5fedc382b241bf3f6",
    productId: "18",
    name: "Graphic T-shirt",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933134/samples/ecommerce/analog-classic.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933160/samples/shoe.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933139/samples/ecommerce/shoes.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933137/samples/food/pot-mussels.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1696933161/samples/balloons.jpg",
    ],
    category: "Teens & Kids",
    subCategory: "Clothes",
    price: 3700,
    description:
      "NIVEA Perfect & Radiant Body Lotion is a daily moisturiser developed to enhance the skin’s natural radiance. The innovative formula of NIVEA Perfect & Radiant Body Lotion gives the desired benefits via combined effect of the active ingredients. It works through two mechanisms:\nEven toned skin by reducing or inhibiting overall skin pigmentation. Active ingredients added to the formula (licorice extract and Octadecenedioic acid) are known to facilitate even toned skin by acting on the melanin producing enzyme, tyrosinase.\nUV protection – The sunscreens added to the formula help in maintaining skin colour by protecting skin from harsh UV rays thus protecting the skin from hyperpigmentation and future skin darkening\n \n\nNIVEA Perfect & Radiant roll-on is enriched with liquorice to visibly lighten underarms for a fairer look, as well as avocado extracts for smoother underarms you can feel. The effective 48h antiperspirant protection ensures you stay dry and smelling nice all day. The gentle NIVEA care formulation is dermatologically approved making it ideal for broken or irritated skin and people who frequently shave.\n\nHow to use\n\nApply the lotion all over your body.\nNo need to wait after lotion application, you can get dressed in seconds\nApply roll on dry underarm\nAllow product to dry completely before dressing\n\n\nINGREDIENTS\nPerfect & Radiant Body Lotion: Water, Dimethicone, Octinoxate, Cetyl Alcohol, Isopropyl Palmitate, Paranum Liquidum, Palmitic Acid, Stearic Acid, Cetyl Palmitate, Avobenzone, Glycyrrhiza Glabra (Licorice) Root Extract, Octadecenedioic Acid, Fragaria Ananassa (Strawberry) Fruit Juice, Rubus Fruticosus (Blackberry) Juice, Rubus Idaeus (Raspberry) Juice, Vaccinium Myrtillus Fruit Juice, Tocopheryl Acetate, Glycerin, Glyceryl Stearate, Propylene Glycol, Arachidic Acid, Myristic Acid, Oleic Acid, Silica,Magnesium Aluminum Silicate, SodiumCarbomer, Trisodium EDTA, Phenoxyethanol, Ethylparaben, Methylparaben, Linalool, Limonene, Alpha-Isomethyl Ionone,Citronellol,Geraniol,BenzylAlcohol,Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde,Benzyl Salicylate,Coumarin,Citral,BHT, Fragrance, Citronellol, Geraniol, BenzylAlcohol, Hydroxyisohexyl 3-CyclohexeneCarboxaldehyde, Benzyl Salicylate, Coumarin, Citral, BHT.",
    tags: ["summer", "formal", "party", "spring", "sports", "sneakers"],
    brand: "Jumia",
    stock: 99,
    sizes: [],
    specifications: {
      color: "grey",
      Size: "40ml",
      material: "glass",
    },
    reviews: [
      {
        userName: "user113",
        reviewTitle: "Reliable",
        reviewMessage: "Met my expectations completely.",
        rating: 4,
        date: "2025-02-10T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3f7",
      },
      {
        userName: "user114",
        reviewTitle: "Reliable",
        reviewMessage: "Color was off, but still usable.",
        rating: 3,
        date: "2025-02-12T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3f8",
      },
      {
        userName: "user115",
        reviewTitle: "Reliable",
        reviewMessage: "Fantastic! Would recommend to friends.",
        rating: 5,
        date: "2025-02-15T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3f9",
      },
      {
        userName: "user110",
        reviewTitle: "Reliable",
        reviewMessage: "Does what it says. Happy with it.",
        rating: 4,
        date: "2025-02-03T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3fa",
      },
      {
        userName: "user111",
        reviewTitle: "Reliable",
        reviewMessage: "Perfect condition and well-packaged.",
        rating: 5,
        date: "2025-02-06T00:00:00.000Z",
        _id: "6859bfd5fedc382b241bf3fb",
      },
    ],
    featured: null,
    sales: 902,
    visits: 23564,
    rating: {
      average: 4,
      reviewsCount: 5,
    },
    __v: 0,
    createdAt: "2025-06-23T20:57:57.239Z",
    updatedAt: "2025-06-23T20:57:57.239Z",
  },
  {
    _id: "6861c710401db710c8ea7885",
    productId: "prod_Cvxde5JE",
    name: "hone",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751238391/download_srchnn.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751238395/ecogreen_tvrgt3.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751238400/error_html_cfbrhh.png",
    ],
    category: "Men",
    subCategory: "Clothes",
    price: 2000,
    description: "jhndbjsnivjnsjijsdojs",
    tags: ["sneakers", "formal", "sandals", "indoor"],
    brand: "Jumia",
    stock: 20,
    sizes: [],
    specifications: {
      color: "red",
    },
    featured: false,
    sales: 0,
    visits: 0,
    rating: {
      average: 0,
      reviewsCount: 0,
    },
    reviews: [],
    createdAt: "2025-06-29T23:06:56.397Z",
    updatedAt: "2025-06-29T23:06:56.397Z",
    __v: 0,
  },
  {
    _id: "686448f76ae0e74f4777fa58",
    productId: "prod_auHuFyYN",
    name: "boredd",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751402716/shuu1_d2xhx8.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751402717/shuu2_zwr2wn.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751402718/shuu3_ksyal4.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751402724/shuu4_ncvfss.jpg",
    ],
    category: "Accessories",
    subCategory: "Clothing Accessories",
    price: 3000,
    description: "kjnsdmodlsd'l,;ads",
    tags: ["party", "dresses", "sneakers", "outdoor", "indoor"],
    brand: "Jumia",
    stock: 21,
    sizes: [],
    specifications: {
      color: "red",
    },
    featured: false,
    sales: 0,
    visits: 0,
    rating: {
      average: 0,
      reviewsCount: 0,
    },
    reviews: [],
    createdAt: "2025-07-01T20:45:43.220Z",
    updatedAt: "2025-07-01T20:59:26.339Z",
    __v: 0,
  },
  {
    _id: "68644c906ae0e74f4777ffa1",
    productId: "prod_TpGIoEr7",
    name: "bored shuu",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403632/5ede7b90448aa-resize-500x500_ty1flb.jpg",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403637/5ede7b90448aa-resize-500x500_ekn5fr.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403650/ayo_xchsz4.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403653/baun_ai_spth99.jpg",
    ],
    category: "Teens & Kids",
    subCategory: "Toys & Games",
    price: 3000,
    description: "jjhbewuhnkeslckmck",
    tags: ["boots", "outdoor", "dresses", "accessories", "travel"],
    brand: "Jumia",
    stock: 21,
    sizes: [],
    specifications: {
      color: "red",
    },
    featured: false,
    sales: 0,
    visits: 0,
    rating: {
      average: 0,
      reviewsCount: 0,
    },
    reviews: [],
    createdAt: "2025-07-01T21:01:04.515Z",
    updatedAt: "2025-07-01T21:01:04.515Z",
    __v: 0,
  },
  {
    _id: "68644d2a6ae0e74f477800e4",
    productId: "prod_xmkMqiXw",
    name: "camee",
    images: [
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403744/error_dghkli.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403765/frame_16_es2svl.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403767/link_ez9xue.png",
      "https://res.cloudinary.com/dtamm3ss1/image/upload/v1751403788/Picture1_i5dy3z.png",
    ],
    category: "Men",
    subCategory: "Clothes",
    price: 3000,
    description: "jnsfnkd;mdojofwe;q;dn",
    tags: ["heels", "sneakers", "spring", "formal", "sports"],
    brand: "Jumia",
    stock: 21,
    sizes: [],
    specifications: {
      color: "red",
    },
    featured: false,
    sales: 0,
    visits: 0,
    rating: {
      average: 0,
      reviewsCount: 0,
    },
    reviews: [],
    createdAt: "2025-07-01T21:03:38.607Z",
    updatedAt: "2025-07-01T21:03:38.607Z",
    __v: 0,
  },
{ brand: "Bershka", category: "Men", createdAt: "2025-08-01T13:24:30.018Z", description: "• EVA Insole : Equipped with an EVA insole, these shoes provide superior cushioning and support for all-day wear.\n\n• Genuine Leather Lining : The genuine leather lining ensures breathability and comfort, enhancing the overall wearing experience.\n\n• Seasonal Versatility : Designed for summer wear, these shoes offer a lightweight and breathable option for warmer climates.\n\n• Top-layer Cowhide Material : Crafted from top-layer cowhide, these shoes offer superior durability and a premium feel, perfect for daily wear.\n\n• British Leather Casual Design : With their classic British leather design, these shoes blend style with functionality, ideal for micro-business settings", featured: false, images: [ "https://res.cloudinary.com/dtamm3ss1/image/upload/v1754054366/rgqfgh19cyspsvb4nbin.jpg", "https://res.cloudinary.com/dtamm3ss1/image/upload/v1754054367/qc1zax2njq5esjjmprak.jpg", "https://res.cloudinary.com/dtamm3ss1/image/upload/v1754054368/fw7hlop7ejhzcqzqaweg.jpg", "https://res.cloudinary.com/dtamm3ss1/image/upload/v1754054369/tofk9xajc8phhudbeypf.jpg", "https://res.cloudinary.com/dtamm3ss1/image/upload/v1754054370/elyfuhzoqfvtrgxxplti.jpg" ], name: "High-End Men's Loafers Classic Sailing Shoes Leather", price: 13450, productId: "prod_sN49ho4h", rating: { average: 0, reviewsCount: 0 }, reviews: [], sales: 0, sizes: [ { form: "EU", value: "40", stock: 10, price: 13450 }, { form: "EU", value: "42", stock: 8, price: 13450 }, { form: "EU", value: "44", stock: 10, price: 13450 } ], specifications: { "Toe Shape": "Round toe", "Shoes Type": "Loafers" }, stock: 28, subCategory: "Shoes", tags: ["dresses", "loafers", "sandals", "leather", "casual"], updatedAt: "2025-08-01T13:24:30.018Z", visits: 0, __v: 0, _id: "688cc00eaaa239fbe970f786" },
];