export const sidebarLinks = [
  {
    id: 1,
    category: "Women",
    subCategory: true,
    name: "women",
    womenSubcategory: [
      "All-products",
      "Women's Clothings",
      "Women's Shoes",
      "Womens Clothing Materials",
    ],
  },
  {
    id: 2,
    category: "Men",
    subCategory: true,
    name: "men",
    menSubcategory: [
      "All-products",
      "Men's Clothings",
      "Men's Shoes",
      "Mens Clothing Materials",
    ],
  },
  {
    id: 3,
    category: "Kids & Baby",
    subCategory: true,
    name: "kids",
    kidsSubcategory: ["All-products", "Kid's Clothing", "Kid's Shoes"],
  },
  {
    id: 4,
    category: "Accessories",
    subCategory: true,
    name: "accessories",
    accessoriesSubcategory: [
      "All-products",
      "Household Accessories",
      "Clothing Accessories",
      "Electronic Accessories",
    ],
  },
  {
    id: 5,
    category: "Shoes",
  },
  {
    id: 6,
    category: "Clothings",
  },
  {
    id: 7,
    category: "Clothing Materials",
  },
  {
    id: 8,
    category: "Accessories",
  },
];

export const categories = [
  {
    id: 1,
    name: "Women's shoes",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 2,
    name: "Men's shoes",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 3,
    name: "Women's clothing",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 4,
    name: "Men's clothing",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 5,
    name: "Clothing materials",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 6,
    name: "Kids and Teens",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 7,
    name: "Accessories",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
  {
    id: 8,
    name: "Clearance",
    image:
      "https://ng.jumia.is/cms/0-1-homepage/0-0-freelinks-gray/300x240/earphones_300x240.png",
  },
];

export const products = [
  {
    id: "001",
    name: "Elegant High Heels",
    description:
      "Stylish women's high heels perfect for parties and formal events.",
    category: "Women Shoes",
    price: 4999,
    currency: "USD",
    brand: "FashionFeet",
    stock: 20,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 75 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      color: "Red",
      size: "38",
      material: "Leather",
    },
    tags: ["heels", "women", "party", "formal"],
    seller: {
      name: "TrendShoe Hub",
      rating: 4.8,
      contact: "contact@trendyshoes.com",
    },
    discount: { percentage: 15, endDate: "2024-12-25" },
    shipping: { free: false, estimatedDelivery: "2-4 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "90876",
        comment: "Comfortable and stylish!",
        rating: 5,
        date: "2024-11-15",
      },
    ],
    featured: true,
  },
  {
    id: "002",
    name: "Men's Leather Loafers",
    description: "Premium leather loafers suitable for casual and formal wear.",
    category: "Men Shoes",
    price: 6599,
    currency: "USD",
    brand: "EliteShoes",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 100 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      color: "Black",
      size: "42",
      material: "Genuine Leather",
    },
    tags: ["loafers", "men", "leather", "casual"],
    seller: {
      name: "Footwear Classics",
      rating: 4.9,
      contact: "support@footclassics.com",
    },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [],
    featured: true,
  },
  {
    id: "003",
    name: "Baby Winter Jacket",
    description: "Warm and cozy jacket for babies during the winter season.",
    category: "Kids and Baby Clothing",
    price: 3599,
    currency: "USD",
    brand: "CozyKids",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 120 },
    sizes: [
      {
        size: "XS",
        stock: 10,
      },
      {
        size: "S",
        stock: 8,
      },
      {
        size: "M",
        stock: 6,
      },
      {
        size: "L",
        stock: 4,
      },
      {
        size: "XL",
        stock: 10,
      },
    ],
    specifications: {
      color: "Blue",
      size: "12 months",
      material: "Wool",
    },
    tags: ["baby", "winter", "jacket"],
    seller: {
      name: "Kids Boutique",
      rating: 4.5,
      contact: "help@kidsboutique.com",
    },
    newArrival: true,
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [],
  },
  {
    id: "W001",
    name: "Elegant High Heels",
    description: "Stylish high heels for formal occasions.",
    category: "Women Shoes",
    price: 7999,
    currency: "NGN",
    brand: "FashionHub",
    stock: 20,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.3, reviews: 95 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Red", size: "38-42", material: "Leather" },
    tags: ["heels", "formal", "women"],
    seller: {
      name: "Shoe Palace",
      rating: 4.6,
      contact: "shoepalace@example.com",
    },
    discount: { percentage: 15, endDate: "2025-01-15" },
    shipping: { free: true, estimatedDelivery: "2-4 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "12456",
        comment: "Very comfortable!",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "67890",
        comment: "Too tight for my size.",
        rating: 3,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "CM002",
    name: "African Ankara Prints",
    description: "High-quality Ankara fabrics for all occasions.",
    category: "Clothing Materials",
    price: 3499,
    currency: "NGN",
    brand: "Textile World",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 150 },
    sizes: [
      {
        size: "XS",
        stock: 10,
      },
      {
        size: "S",
        stock: 8,
      },
      {
        size: "M",
        stock: 6,
      },
      {
        size: "L",
        stock: 4,
      },
      {
        size: "XL",
        stock: 10,
      },
    ],
    specifications: { color: "Multicolor", material: "Cotton" },
    tags: ["Ankara", "fabric", "traditional"],
    seller: {
      name: "Ankara Hub",
      rating: 4.9,
      contact: "ankarahub@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-31" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "34567",
        comment: "Amazing fabric!",
        rating: 5,
        date: "2024-11-25",
      },
      {
        userId: "78901",
        comment: "Color fades after wash.",
        rating: 3,
        date: "2024-11-20",
      },
    ],
  },
  {
    id: "M001",
    name: "Classic Leather Loafers",
    description: "Comfortable and durable leather loafers for daily wear.",
    category: "Men Shoes",
    price: 12999,
    currency: "NGN",
    brand: "StepMax",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.4, reviews: 80 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Brown", size: "40-45", material: "Leather" },
    tags: ["loafers", "men", "casual"],
    seller: {
      name: "Classic Shoes Ltd.",
      rating: 4.5,
      contact: "classics@example.com",
    },
    discount: { percentage: 5, endDate: "2025-01-01" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "54321",
        comment: "Stylish and comfortable.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "67899",
        comment: "Slightly tight for wider feet.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
    featured: true,
  },
  {
    id: "K001",
    name: "Colorful Sneakers",
    description: "Vibrant sneakers for kids' everyday adventures.",
    category: "Kids and Baby Shoes",
    price: 4999,
    currency: "NGN",
    brand: "HappyFeet",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 55 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Blue", size: "25-35", material: "Fabric" },
    tags: ["sneakers", "kids", "shoes"],
    seller: {
      name: "KidZone Store",
      rating: 4.8,
      contact: "kidzone@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "12567",
        comment: "My son loves them!",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "87954",
        comment: "The color is amazing.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "H001",
    name: "Wall-Mounted Storage Racks",
    description: "Durable and space-saving racks for organizing your home.",
    category: "Household Accessories",
    price: 11999,
    currency: "NGN",
    brand: "HomeStyle",
    stock: 15,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.2, reviews: 60 },
    specifications: {
      color: "White",
      dimensions: "50x20x10 cm",
      material: "Metal",
    },
    tags: ["storage", "organization", "household"],
    seller: {
      name: "Home Haven",
      rating: 4.7,
      contact: "homehaven@example.com",
    },
    discount: { percentage: 20, endDate: "2025-02-01" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "65823",
        comment: "Great for small spaces!",
        rating: 5,
        date: "2024-11-25",
      },
      {
        userId: "54789",
        comment: "A bit hard to install.",
        rating: 3,
        date: "2024-11-22",
      },
    ],
    newArrival: true, // Marked as a new arrival
  },
  {
    id: "W002",
    name: "Elegant Stiletto Heels",
    description:
      "Stylish and elegant stiletto heels perfect for formal occasions.",
    category: "Women Shoes",
    price: 15999,
    currency: "NGN",
    brand: "Fashionista",
    stock: 25,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 45 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Red", size: "38-42", material: "Synthetic" },
    tags: ["heels", "stiletto", "women"],
    seller: { name: "Glam Hub", rating: 4.8, contact: "glamhub@example.com" },
    discount: { percentage: 15, endDate: "2024-12-25" },
    shipping: { free: true, estimatedDelivery: "2-4 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "43567",
        comment: "Looks stunning and fits well!",
        rating: 5,
        date: "2024-12-03",
      },
      {
        userId: "23548",
        comment: "Not comfortable for long hours.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "CM0022",
    name: "Ankara Wax Prints",
    description: "Vibrant and high-quality Ankara fabric for tailored designs.",
    category: "Clothing Materials",
    price: 8999,
    currency: "NGN",
    brand: "African Heritage",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 70 },
    sizes: [
      {
        size: "XS",
        stock: 10,
      },
      {
        size: "S",
        stock: 8,
      },
      {
        size: "M",
        stock: 6,
      },
      {
        size: "L",
        stock: 4,
      },
      {
        size: "XL",
        stock: 10,
      },
    ],
    specifications: { length: "6 yards", material: "Cotton" },
    tags: ["ankara", "fabric", "tailoring"],
    seller: {
      name: "Heritage Fabrics",
      rating: 4.9,
      contact: "heritage@example.com",
    },
    discount: { percentage: 10, endDate: "2025-01-15" },
    shipping: { free: false, estimatedDelivery: "3-6 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "72345",
        comment: "Perfect for traditional attire.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "54321",
        comment: "Colors fade after a few washes.",
        rating: 3,
        date: "2024-11-25",
      },
    ],
    featured: true, // Highlighted product of the day
  },
  {
    id: "CA001",
    name: "Leather Belt",
    description: "Classic leather belt with adjustable buckle.",
    category: "Clothing Accessories",
    price: 2999,
    currency: "NGN",
    brand: "BeltCo",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.3, reviews: 35 },
    specifications: { color: "Black", material: "Genuine Leather" },
    tags: ["belt", "men", "accessories"],
    seller: {
      name: "Accessory World",
      rating: 4.6,
      contact: "accessoryworld@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-20" },
    shipping: { free: false, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "21356",
        comment: "Stylish and durable.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "12456",
        comment: "The buckle feels a bit flimsy.",
        rating: 3,
        date: "2024-11-29",
      },
    ],
    newArrival: true, // Marked as a new arrival
  },
  {
    id: "M003",
    name: "Formal Leather Shoes",
    description: "Premium leather shoes designed for formal events.",
    category: "Men Shoes",
    price: 25999,
    currency: "NGN",
    brand: "UrbanStyle",
    stock: 30,
     images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 80 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      color: "Brown",
      material: "Genuine Leather",
      size: "41-45",
    },
    tags: ["formal", "shoes", "leather"],
    seller: {
      name: "Gentlemen's Club",
      rating: 4.9,
      contact: "gentlemenclub@example.com",
    },
    discount: { percentage: 20, endDate: "2024-12-31" },
    shipping: { free: true, estimatedDelivery: "2-3 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "45789",
        comment: "Perfect fit and top-notch quality.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "37890",
        comment: "Slightly heavy but looks great.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
    featured: true, // Featured as a main product of the day
  },
  {
    id: "KC001",
    name: "Baby Romper Set",
    description: "Soft cotton baby romper set with adorable prints.",
    category: "Kids and Baby Clothing",
    price: 4999,
    currency: "NGN",
    brand: "BabyComfort",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 60 },
    sizes: [
      {
        size: "XS",
        stock: 10,
      },
      {
        size: "S",
        stock: 8,
      },
      {
        size: "M",
        stock: 6,
      },
      {
        size: "L",
        stock: 4,
      },
      {
        size: "XL",
        stock: 10,
      },
    ],
    specifications: {
      size: "0-12 months",
      material: "Cotton",
      packSize: "3 pieces",
    },
    tags: ["baby", "romper", "clothing"],
    seller: {
      name: "ComfortKids",
      rating: 4.8,
      contact: "comfortkids@example.com",
    },
    discount: { percentage: 12, endDate: "2024-12-29" },
    shipping: { free: false, estimatedDelivery: "4-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "56234",
        comment: "Soft material and fits perfectly.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "67231",
        comment: "Print faded after washing.",
        rating: 4,
        date: "2024-11-27",
      },
    ],
    newArrival: true, // Marked as a new arrival
  },
  {
    id: "HA001",
    name: "Multipurpose Organizer",
    description: "Compact organizer for storing various household items.",
    category: "Household Accessories",
    price: 7999,
    currency: "NGN",
    brand: "NeatSpace",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 50 },
    specifications: {
      dimensions: "25x15x10 cm",
      material: "Plastic",
      compartments: "6",
    },
    tags: ["organizer", "household", "accessories"],
    seller: {
      name: "HomeEssentials",
      rating: 4.7,
      contact: "homeessentials@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-31" },
    shipping: { free: false, estimatedDelivery: "5-8 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "43521",
        comment: "Keeps everything organized.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "34251",
        comment: "A bit smaller than expected.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "WS004",
    name: "Stylish High Heels",
    description: "Elegant high heels perfect for formal and casual outings.",
    category: "Women Shoes",
    price: 18999,
    currency: "NGN",
    brand: "ChicSteps",
    stock: 25,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 120 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Red", size: "38-43", material: "Faux Leather" },
    tags: ["heels", "women", "fashion"],
    seller: {
      name: "StyleCorner",
      rating: 4.8,
      contact: "stylecorner@example.com",
    },
    discount: { percentage: 15, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "2-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "56723",
        comment: "Amazing comfort and looks beautiful.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "67841",
        comment: "Color is slightly darker than pictured.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
    featured: true, // Featured as a main product of the day
  },
  {
    id: "KS002",
    name: "Children's Sports Sneakers",
    description: "Durable sneakers designed for active kids.",
    category: "Kids and Baby Shoes",
    price: 12999,
    currency: "NGN",
    brand: "ActiveKids",
    stock: 35,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 75 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Blue", size: "28-35", material: "Synthetic" },
    tags: ["kids", "shoes", "sneakers"],
    seller: {
      name: "KidActive Store",
      rating: 4.7,
      contact: "kidactive@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-25" },
    shipping: { free: false, estimatedDelivery: "3-6 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "87901",
        comment: "Sturdy and looks great on my kid.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "78012",
        comment: "Laces are a bit too long.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
    newArrival: true, // Marked as a new arrival
  },
  {
    id: "CA002",
    name: "Silk Scarf",
    description: "Elegant silk scarf to complement your outfit.",
    category: "Clothing Accessories",
    price: 5999,
    currency: "NGN",
    brand: "FashionSilk",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 50 },
    specifications: {
      material: "Silk",
      dimensions: "90x90 cm",
      color: "Multicolor",
    },
    tags: ["scarf", "accessory", "silk"],
    seller: {
      name: "ElegantWear",
      rating: 4.9,
      contact: "elegantwear@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: false, estimatedDelivery: "4-7 business days" },
    addedToCart: true,
    wishlist: true,
    reviews: [
      {
        userId: "23489",
        comment: "Feels luxurious and looks amazing.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "67432",
        comment: "A bit pricey but worth it.",
        rating: 5,
        date: "2024-11-27",
      },
    ],
  },
  {
    id: "MS003",
    name: "Casual Loafers",
    description: "Comfortable and stylish loafers for daily wear.",
    category: "Men Shoes",
    price: 15999,
    currency: "NGN",
    brand: "UrbanStyle",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.4, reviews: 85 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Brown", size: "40-45", material: "Leather" },
    tags: ["men", "shoes", "loafers"],
    seller: {
      name: "UrbanWear Store",
      rating: 4.6,
      contact: "urbanwear@example.com",
    },
    discount: { percentage: 20, endDate: "2024-12-31" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "12009",
        comment: "Super comfy and stylish.",
        rating: 5,
        date: "2024-12-03",
      },
      {
        userId: "76432",
        comment: "Sizing runs slightly small.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
    featured: true, // Featured as a main product of the day
  },
  {
    id: "KS002",
    name: "Velcro Strap Sneakers",
    description:
      "Lightweight and easy-to-wear sneakers for kids, featuring velcro straps for convenience.",
    category: "Kids and Baby Shoes",
    price: 9999,
    currency: "NGN",
    brand: "KidFit",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 60 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Blue", size: "20-30", material: "Fabric" },
    tags: ["kids", "shoes", "sneakers"],
    seller: {
      name: "LittleSteps",
      rating: 4.5,
      contact: "littlesteps@example.com",
    },
    discount: { percentage: 15, endDate: "2024-12-25" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "65321",
        comment: "Durable and stylish, my kids love them!",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "78910",
        comment: "Great value for money.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
    newArrival: true, // Marked as a new arrival
  },
  {
    id: "CM004",
    name: "African Print Fabric",
    description:
      "Premium quality African print fabric, perfect for traditional outfits.",
    category: "Clothing Materials",
    price: 6999,
    currency: "NGN",
    brand: "NaijaPrints",
    stock: 100,
     images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 150 },
    sizes: [
      {
        size: "XS",
        stock: 10,
      },
      {
        size: "S",
        stock: 8,
      },
      {
        size: "M",
        stock: 6,
      },
      {
        size: "L",
        stock: 4,
      },
      {
        size: "XL",
        stock: 10,
      },
    ],
    specifications: {
      color: "Multicolor",
      length: "6 yards",
      material: "Cotton",
    },
    tags: ["fabric", "african print", "materials"],
    seller: {
      name: "StyleCraft",
      rating: 4.9,
      contact: "stylecraft@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-31" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: true,
    wishlist: true,
    reviews: [
      {
        userId: "90321",
        comment: "Beautiful design and high-quality fabric.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "56023",
        comment: "Colors are even more vibrant than the picture.",
        rating: 5,
        date: "2024-11-29",
      },
    ],
    featured: true, // Featured as a main product of the day
  },
  {
    id: "HA002",
    name: "Wall-Mounted Storage Hooks",
    description:
      "Durable wall-mounted hooks for organizing your home effortlessly.",
    category: "Household Accessories",
    price: 2999,
    currency: "NGN",
    brand: "SmartSpace",
    stock: 80,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.3, reviews: 45 },
    specifications: { material: "Metal", packSize: "6 hooks", color: "Silver" },
    tags: ["hooks", "organization", "household"],
    seller: {
      name: "HomeEssentials",
      rating: 4.5,
      contact: "homeessentials@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-20" },
    shipping: { free: false, estimatedDelivery: "3-6 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "89213",
        comment: "Great for organizing my kitchen.",
        rating: 4,
        date: "2024-11-27",
      },
      {
        userId: "76432",
        comment: "Simple and effective.",
        rating: 5,
        date: "2024-11-30",
      },
    ],
    newArrival: true, // Marked as a new arrival
  },
  {
    id: "WS005",
    name: "Block Heel Sandals",
    description:
      "Stylish block heel sandals with an adjustable strap, perfect for any occasion.",
    category: "Women Shoes",
    price: 11999,
    currency: "NGN",
    brand: "GlamStep",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 85 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      color: "Beige",
      heelHeight: "3 inches",
      material: "Leather",
    },
    tags: ["shoes", "sandals", "women"],
    seller: {
      name: "EleganceHub",
      rating: 4.6,
      contact: "elegancehub@example.com",
    },
    discount: { percentage: 20, endDate: "2024-12-24" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "87321",
        comment: "Comfortable and elegant.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "67345",
        comment: "Exactly as described.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
    featured: true, // Marked as a main product of the day
  },
  {
    id: "MS003",
    name: "Oxford Leather Shoes",
    description:
      "Classic Oxford shoes made with premium leather for formal and casual use.",
    category: "Men Shoes",
    price: 18999,
    currency: "NGN",
    brand: "UrbanClassic",
    stock: 45,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 60 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Brown", size: "40-46", material: "Leather" },
    tags: ["shoes", "formal", "men"],
    seller: {
      name: "StyleVault",
      rating: 4.8,
      contact: "stylevault@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-31" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "98123",
        comment: "High-quality and durable.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "57432",
        comment: "Comfortable for all-day wear.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
    featured: true, // Marked as a main product of the day
  },
  {
    id: "CA003",
    name: "Silk Necktie",
    description:
      "Premium silk necktie available in various patterns and colors.",
    category: "Clothing Accessories",
    price: 4999,
    currency: "NGN",
    brand: "TieMasters",
    stock: 70,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 95 },
    specifications: {
      material: "Silk",
      length: "58 inches",
      width: "3 inches",
    },
    tags: ["necktie", "accessories", "formal"],
    seller: {
      name: "GentStyle",
      rating: 4.7,
      contact: "gentstyle@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-29" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: true,
    wishlist: true,
    reviews: [
      {
        userId: "65345",
        comment: "Smooth fabric and classy design.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "67432",
        comment: "Matches perfectly with my suit.",
        rating: 5,
        date: "2024-11-29",
      },
    ],
    featured: true, // Marked as a main product of the day
  },
  {
    id: "KBS001",
    name: "Toddler Sneakers",
    description:
      "Comfortable sneakers for toddlers, with soft soles and vibrant colors.",
    category: "Kids and Baby Shoes",
    price: 8499,
    currency: "NGN",
    brand: "TinySteps",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 120 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Blue", size: "20-24", material: "Canvas" },
    tags: ["baby shoes", "sneakers", "kids"],
    seller: {
      name: "BabyTrend",
      rating: 4.5,
      contact: "babytrend@example.com",
    },
    discount: { percentage: 15, endDate: "2024-12-30" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "71239",
        comment: "My kid loves them!",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "82394",
        comment: "Cute design, but a bit small.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "WS006",
    name: "Flat Ballet Shoes",
    description:
      "Classic flat ballet shoes designed for comfort and style in daily wear.",
    category: "Women Shoes",
    price: 4999,
    currency: "NGN",
    brand: "EleganceBallet",
    stock: 80,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.4, reviews: 95 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Black", size: "35-41", material: "Leather" },
    tags: ["shoes", "ballet flats", "women"],
    seller: {
      name: "BalletBeauty",
      rating: 4.7,
      contact: "balletbeauty@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "99274",
        comment: "Very comfortable and soft.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "84392",
        comment: "Nice, but the size runs a bit small.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "EA001",
    name: "USB-C to Lightning Cable",
    description:
      "High-speed data transfer and charging USB-C to Lightning cable, durable and tangle-free.",
    category: "Electronic Accessories",
    price: 2499,
    currency: "NGN",
    brand: "PowerLink",
    stock: 100,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 150 },
    specifications: {
      color: "White",
      length: "1 meter",
      material: "Nylon braided",
    },
    tags: ["cable", "charger", "accessories"],
    seller: {
      name: "GadgetStore",
      rating: 4.8,
      contact: "gadgetstore@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "2-4 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "46238",
        comment: "Fast charging and durable.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "78165",
        comment: "Great quality, highly recommend!",
        rating: 5,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "MS004",
    name: "Running Sneakers",
    description:
      "Lightweight running sneakers with shock-absorbing soles for comfortable workouts.",
    category: "Men Shoes",
    price: 14999,
    currency: "NGN",
    brand: "FlexRun",
    stock: 65,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 110 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: { color: "Grey", size: "40-46", material: "Mesh" },
    tags: ["sneakers", "running shoes", "men"],
    seller: { name: "FlexGear", rating: 4.9, contact: "flexgear@example.com" },
    discount: { percentage: 20, endDate: "2024-12-30" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "82347",
        comment: "Perfect for running, very comfy.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "47456",
        comment: "Good sneakers but a bit tight.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "CA004",
    name: "Woolen Scarf",
    description:
      "Soft and warm woolen scarf for chilly weather, available in multiple colors.",
    category: "Clothing Accessories",
    price: 3999,
    currency: "NGN",
    brand: "CozyThreads",
    stock: 120,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 80 },
    specifications: {
      material: "Wool",
      length: "70 inches",
      width: "8 inches",
    },
    tags: ["scarf", "wool", "accessories"],
    seller: {
      name: "WarmEssence",
      rating: 4.7,
      contact: "warmessence@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "5-7 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "57439",
        comment: "Warm and cozy, perfect for winter.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "73842",
        comment: "Good quality, but a little itchy.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "CM001",
    name: "Cotton Fabric (Light Pink)",
    description:
      "Soft and breathable cotton fabric, perfect for making dresses, shirts, and other garments.",
    category: "Clothing Materials",
    price: 2499,
    currency: "NGN",
    brand: "FabricLand",
    stock: 200,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 70 },
    specifications: {
      color: "Light Pink",
      material: "Cotton",
      width: "1 meter",
    },
    tags: ["fabric", "cotton", "sewing", "clothing material"],
    seller: {
      name: "FabricMasters",
      rating: 4.6,
      contact: "fabricmasters@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-15" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "84762",
        comment: "Very soft fabric, great for dresses!",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "57394",
        comment: "Nice color, but a bit thin.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "KBC002",
    name: "Baby Pajamas Set",
    description:
      "Comfortable and cute baby pajama set made from soft cotton fabric, perfect for a good night's sleep.",
    category: "Kids and Baby Clothing",
    price: 2999,
    currency: "NGN",
    brand: "TinyDreams",
    stock: 150,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 50 },
    sizes: [
      {
        size: "XS",
        stock: 10,
      },
      {
        size: "S",
        stock: 8,
      },
      {
        size: "M",
        stock: 6,
      },
      {
        size: "L",
        stock: 4,
      },
      {
        size: "XL",
        stock: 10,
      },
    ],
    specifications: { color: "Pink", size: "0-3 months", material: "Cotton" },
    tags: ["baby pajamas", "sleepwear", "cotton"],
    seller: { name: "BabyWear", rating: 4.7, contact: "babywear@example.com" },
    discount: { percentage: 10, endDate: "2024-12-10" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "49162",
        comment: "So soft and cozy!",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "72319",
        comment: "Cute set, but a little small for my baby.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "HA001",
    name: "LED Night Lamp",
    description:
      "Compact LED night lamp with adjustable brightness, perfect for any room.",
    category: "Household Accessories",
    price: 3999,
    currency: "NGN",
    brand: "HomeGlow",
    stock: 75,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 30 },
    specifications: { color: "White", power: "USB", material: "Plastic" },
    tags: ["night lamp", "LED", "lighting"],
    seller: {
      name: "HomeEssentials",
      rating: 4.4,
      contact: "homeessentials@example.com",
    },
    discount: { percentage: 20, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "19834",
        comment: "Nice lamp, great for my kid's room.",
        rating: 4,
        date: "2024-12-01",
      },
      {
        userId: "29472",
        comment: "Good lamp, but it’s too dim.",
        rating: 3,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "CA005",
    name: "Leather Belt",
    description:
      "Stylish leather belt available in black and brown, perfect for both formal and casual wear.",
    category: "Clothing Accessories",
    price: 4999,
    currency: "NGN",
    brand: "StyleCraft",
    stock: 120,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 90 },
    specifications: { color: "Black", size: "30-40", material: "Leather" },
    tags: ["belt", "leather", "accessories"],
    seller: {
      name: "FashionCorner",
      rating: 4.6,
      contact: "fashioncorner@example.com",
    },
    discount: { percentage: 15, endDate: "2024-12-25" },
    shipping: { free: false, estimatedDelivery: "4-6 business days" },
    addedToCart: true,
    wishlist: true,
    reviews: [
      {
        userId: "93829",
        comment: "Great quality leather, highly recommend!",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "28293",
        comment: "Good belt, but the size is a bit off.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "HA002",
    name: "Portable Fan",
    description:
      "Rechargeable mini portable fan, perfect for on-the-go cooling during hot weather.",
    category: "Household Accessories",
    price: 2499,
    currency: "NGN",
    brand: "CoolBreeze",
    stock: 200,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.3, reviews: 110 },
    specifications: {
      color: "Blue",
      material: "Plastic",
      batteryLife: "5 hours",
    },
    tags: ["fan", "portable", "cooling"],
    seller: { name: "AirPlus", rating: 4.5, contact: "airplus@example.com" },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "65739",
        comment: "Nice fan, but a little noisy.",
        rating: 4,
        date: "2024-11-30",
      },
      {
        userId: "18392",
        comment: "Really powerful for its size!",
        rating: 5,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "EA003",
    name: "Portable Power Bank",
    description:
      "Compact 10000mAh power bank for charging your devices on the go.",
    category: "Electronic Accessories",
    price: 4599,
    currency: "NGN",
    brand: "PowerGo",
    stock: 100,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 75 },
    specifications: {
      capacity: "10000mAh",
      material: "Plastic",
      output: "2 USB ports",
    },
    tags: ["power bank", "electronics", "portable charger"],
    seller: { name: "ChargeIt", rating: 4.7, contact: "chargeit@example.com" },
    discount: { percentage: 5, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "12472",
        comment: "Charges my phone quickly, great product!",
        rating: 5,
        date: "2024-11-29",
      },
      {
        userId: "34856",
        comment: "It works, but it gets a little hot when charging.",
        rating: 3,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "KA003",
    name: "Electric Kettle",
    description:
      "1.7L electric kettle with rapid boiling technology, automatic shut-off feature, and boil-dry protection.",
    category: "Kitchen Appliances",
    price: 6999,
    currency: "NGN",
    brand: "HomeTech",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 120 },
    specifications: {
      color: "Silver",
      capacity: "1.7L",
      material: "Stainless Steel",
    },
    tags: ["electric kettle", "kitchen appliance", "boiling water"],
    seller: {
      name: "HomeGoods",
      rating: 4.6,
      contact: "homegoods@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-30" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "34912",
        comment: "Boils water fast, great for tea lovers.",
        rating: 5,
        date: "2024-11-29",
      },
      {
        userId: "56219",
        comment: "Love the design, but a little loud when boiling.",
        rating: 4,
        date: "2024-11-27",
      },
    ],
  },
  {
    id: "FA003",
    name: "Unisex Sunglasses",
    description:
      "Trendy unisex sunglasses with UV protection and stylish frames available in black and brown.",
    category: "Fashion Accessories",
    price: 3499,
    currency: "NGN",
    brand: "SunStyle",
    stock: 75,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.4, reviews: 50 },
    specifications: {
      color: "Black",
      material: "Plastic",
      lens: "UV400 protection",
    },
    tags: ["sunglasses", "fashion", "accessory"],
    seller: {
      name: "FashionTrends",
      rating: 4.7,
      contact: "fashiontrends@example.com",
    },
    discount: { percentage: 15, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "47302",
        comment: "Great quality and looks stylish.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "23591",
        comment: "The frames are a little loose.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "FU005",
    name: "Wooden Coffee Table",
    description:
      "Elegant wooden coffee table with a modern design and ample space for storage.",
    category: "Furniture",
    price: 12499,
    currency: "NGN",
    brand: "WoodCraft",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 30 },
    specifications: { material: "Wood", color: "Brown", size: "120x60x45 cm" },
    tags: ["coffee table", "furniture", "wooden"],
    seller: {
      name: "CraftedLiving",
      rating: 4.5,
      contact: "craftedliving@example.com",
    },
    discount: { percentage: 20, endDate: "2024-12-31" },
    shipping: { free: true, estimatedDelivery: "7-10 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "12983",
        comment: "Very sturdy and spacious. Perfect for my living room.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "68234",
        comment: "Nice table, but the assembly was tricky.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "HA003",
    name: "Washing Machine",
    description:
      "Automatic washing machine with multiple wash cycles, energy-efficient, and easy to use.",
    category: "Home Appliances",
    price: 49999,
    currency: "NGN",
    brand: "CleanSpin",
    stock: 25,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 65 },
    specifications: { type: "Automatic", capacity: "7kg", energyClass: "A+" },
    tags: ["washing machine", "home appliance", "laundry"],
    seller: {
      name: "CleanTech",
      rating: 4.8,
      contact: "cleantech@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-10" },
    shipping: { free: false, estimatedDelivery: "7-10 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "90232",
        comment: "Does a great job cleaning clothes!",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "11902",
        comment: "Good washing machine, but quite noisy.",
        rating: 4,
        date: "2024-11-27",
      },
    ],
  },
  {
    id: "BC003",
    name: "Facial Cleanser",
    description:
      "Gentle facial cleanser suitable for all skin types, removes dirt and makeup, leaves skin smooth and refreshed.",
    category: "Beauty and Personal Care",
    price: 1999,
    currency: "NGN",
    brand: "PureGlow",
    stock: 120,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 90 },
    specifications: {
      size: "200ml",
      skinType: "All",
      ingredients: "Aloe Vera, Chamomile",
    },
    tags: ["facial cleanser", "skincare", "beauty"],
    seller: { name: "GlowSkin", rating: 4.6, contact: "glowskin@example.com" },
    discount: { percentage: 20, endDate: "2024-12-25" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "57463",
        comment: "Leaves my skin feeling fresh!",
        rating: 5,
        date: "2024-11-29",
      },
      {
        userId: "18437",
        comment: "A bit too strong for sensitive skin.",
        rating: 3,
        date: "2024-11-27",
      },
    ],
  },
  {
    id: "BP003",
    name: "Baby Diapers (Pack of 20)",
    description:
      "Soft and absorbent baby diapers, designed for maximum comfort and leak protection.",
    category: "Baby Products",
    price: 1599,
    currency: "NGN",
    brand: "BabySoft",
    stock: 150,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 110 },
    specifications: { count: 20, size: "Small", material: "Cotton" },
    tags: ["baby diapers", "baby care", "soft"],
    seller: { name: "BabyCare", rating: 4.8, contact: "babycare@example.com" },
    discount: { percentage: 5, endDate: "2024-12-10" },
    shipping: { free: false, estimatedDelivery: "3-5 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "20389",
        comment: "Very soft and absorbent, my baby loves it!",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "47293",
        comment: "A little expensive for the quantity.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "SO004",
    name: "Yoga Mat",
    description:
      "Non-slip, thick yoga mat perfect for all levels of practice. Made from eco-friendly materials for durability and comfort.",
    category: "Sports & Outdoors",
    price: 2999,
    currency: "NGN",
    brand: "FitLife",
    stock: 80,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 45 },
    specifications: { color: "Purple", material: "TPE", size: "183x61 cm" },
    tags: ["yoga mat", "exercise", "fitness"],
    seller: {
      name: "FitnessWorld",
      rating: 4.7,
      contact: "fitnessworld@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-20" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "35081",
        comment: "Great quality and non-slip, perfect for yoga!",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "82109",
        comment: "Very comfortable to use during my workouts.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "MP007",
    name: "Smartphone X1",
    description:
      "6.5-inch screen smartphone with 128GB storage, 48MP camera, and 4000mAh battery. Runs on Android 12.",
    category: "Mobile Phones & Tablets",
    price: 79999,
    currency: "NGN",
    brand: "TechMobile",
    stock: 60,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 110 },
    specifications: {
      color: "Black",
      storage: "128GB",
      camera: "48MP",
      battery: "4000mAh",
    },
    tags: ["smartphone", "mobile phone", "android"],
    seller: {
      name: "MobileWorld",
      rating: 4.9,
      contact: "mobileworld@example.com",
    },
    discount: { percentage: 15, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "82763",
        comment: "Great performance and camera quality.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "15329",
        comment: "Battery life could be better.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "CL008",
    name: "Laptop Pro 15",
    description:
      "15-inch laptop with 8GB RAM, 512GB SSD, and Intel i7 processor. Ideal for work and entertainment.",
    category: "Computers & Laptops",
    price: 199999,
    currency: "NGN",
    brand: "TechnoCore",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 40 },
    specifications: {
      color: "Silver",
      RAM: "8GB",
      storage: "512GB SSD",
      processor: "Intel i7",
    },
    tags: ["laptop", "computers", "electronics"],
    seller: {
      name: "TechnoHub",
      rating: 4.9,
      contact: "technohub@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-31" },
    shipping: { free: false, estimatedDelivery: "7-10 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "47391",
        comment: "Excellent laptop for work and gaming.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "56328",
        comment: "A bit expensive but great performance.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "HA004",
    name: "Microwave Oven",
    description:
      "800W microwave oven with defrost and auto-cook functions. Ideal for fast and easy meal preparation.",
    category: "Home Appliances",
    price: 12999,
    currency: "NGN",
    brand: "QuickCook",
    stock: 45,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 90 },
    specifications: {
      power: "800W",
      features: ["Defrost", "Auto-cook"],
      color: "White",
    },
    tags: ["microwave", "home appliance", "kitchen"],
    seller: {
      name: "QuickKitchen",
      rating: 4.6,
      contact: "quickkitchen@example.com",
    },
    discount: { percentage: 12, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "84265",
        comment: "Microwave works great and heats food evenly.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "65291",
        comment: "A little bulky but good overall.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "AU005",
    name: "Car Seat Cover Set",
    description:
      "Complete set of car seat covers made with durable fabric for protection and comfort. Fits most car models.",
    category: "Automotive",
    price: 8499,
    currency: "NGN",
    brand: "AutoCare",
    stock: 60,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.4, reviews: 80 },
    specifications: { material: "Durable fabric", color: "Black", setCount: 5 },
    tags: ["car accessories", "car seat cover", "automotive"],
    seller: { name: "AutoZone", rating: 4.8, contact: "autozone@example.com" },
    discount: { percentage: 8, endDate: "2024-12-25" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "92134",
        comment: "Good quality, fits well in my car.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "10329",
        comment: "A bit tight on my seat, but still good.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "HK006",
    name: "Blender Pro 1000",
    description:
      "High-speed blender with 1000W power for smoothies, soups, and more. Includes two 500ml jars.",
    category: "Home & Kitchen",
    price: 14999,
    currency: "NGN",
    brand: "BlendMaster",
    stock: 75,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 110 },
    specifications: { power: "1000W", jars: "2x500ml", color: "Black" },
    tags: ["blender", "kitchen appliance", "smoothies"],
    seller: {
      name: "HomeEssentials",
      rating: 4.9,
      contact: "homeessentials@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: false, estimatedDelivery: "3-5 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "87129",
        comment: "Powerful blender, makes great smoothies!",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "10328",
        comment: "A bit noisy, but effective.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "KB008",
    name: "Baby Stroller",
    description:
      "Lightweight and durable stroller with adjustable reclining seat and safety harness. Suitable for newborns and toddlers.",
    category: "Kids & Baby",
    price: 24999,
    currency: "NGN",
    brand: "BabyCare",
    stock: 50,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 85 },
    specifications: { color: "Blue", material: "Aluminum", weight: "6.5 kg" },
    tags: ["baby stroller", "kids", "baby care"],
    seller: {
      name: "BabyWorld",
      rating: 4.8,
      contact: "babyworld@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-10" },
    shipping: { free: true, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "96250",
        comment: "Sturdy and easy to maneuver.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "24109",
        comment: "Could use a bigger storage basket.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "BC007",
    name: "Cotton Baby Onesie",
    description:
      "Soft cotton onesie for babies, with easy snap buttons for quick changes. Available in multiple colors.",
    category: "Baby Clothing",
    price: 1799,
    currency: "NGN",
    brand: "CuteBaby",
    stock: 100,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 50 },
    specifications: {
      color: "White",
      material: "Cotton",
      sizes: ["0-6 months", "6-12 months"],
    },
    tags: ["baby clothes", "onesie", "cotton"],
    seller: {
      name: "BabyStyle",
      rating: 4.8,
      contact: "babystyle@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-12" },
    shipping: { free: false, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "72409",
        comment: "Soft and gentle on baby's skin.",
        rating: 5,
        date: "2024-11-29",
      },
      {
        userId: "59271",
        comment: "Nice fit, but could be slightly larger.",
        rating: 4,
        date: "2024-11-27",
      },
    ],
  },
  {
    id: "MS003",
    name: "Leather Oxford Shoes",
    description:
      "Premium leather Oxford shoes with a classic design. Perfect for formal occasions and professional settings.",
    category: "Men's Shoes",
    price: 11999,
    currency: "NGN",
    brand: "StyleMan",
    stock: 40,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 75 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      color: "Black",
      material: "Leather",
      size: "42, 43, 44, 45",
    },
    tags: ["oxford shoes", "leather shoes", "formal wear"],
    seller: {
      name: "FashionFeet",
      rating: 4.9,
      contact: "fashionfeet@example.com",
    },
    discount: { percentage: 8, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "48239",
        comment: "Great quality leather shoes, highly recommend.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "94276",
        comment: "A little tight but looks very classy.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "HD010",
    name: "Modern Wall Clock",
    description:
      "Sleek, modern design wall clock that fits in with contemporary home decor. Silent ticking for a peaceful environment.",
    category: "Home Decor",
    price: 7999,
    currency: "NGN",
    brand: "TimeCraft",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 60 },
    specifications: { material: "Metal", color: "Silver", size: "30cm" },
    tags: ["wall clock", "home decor", "modern"],
    seller: {
      name: "DecorStyle",
      rating: 4.7,
      contact: "decorstyle@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-10" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "63025",
        comment: "Very stylish and silent, love it!",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "37908",
        comment: "Looks good but a bit heavy to mount.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "HA012",
    name: "Cordless Vacuum Cleaner",
    description:
      "Portable and powerful cordless vacuum cleaner with a detachable dustbin for easy cleaning and long battery life.",
    category: "Household Accessories",
    price: 25999,
    currency: "NGN",
    brand: "CleanPro",
    stock: 60,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 95 },
    specifications: {
      batteryLife: "60 minutes",
      weight: "2.5 kg",
      color: "Red",
    },
    tags: ["vacuum cleaner", "cordless", "household"],
    seller: {
      name: "HomeTools",
      rating: 4.8,
      contact: "hometools@example.com",
    },
    discount: { percentage: 12, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "5-7 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "91508",
        comment: "Very efficient, lightweight, and easy to use.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "35701",
        comment: "Great product, but battery life could be longer.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "CA009",
    name: "Leather Wallet",
    description:
      "Sleek and stylish genuine leather wallet with multiple compartments for cards and cash. Available in black and brown.",
    category: "Clothing Accessories",
    price: 8499,
    currency: "NGN",
    brand: "LuxStyle",
    stock: 80,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 70 },
    specifications: {
      material: "Genuine Leather",
      color: "Black",
      size: "Medium",
    },
    tags: ["wallet", "leather", "fashion accessories"],
    seller: { name: "LuxStore", rating: 4.9, contact: "luxstore@example.com" },
    discount: { percentage: 15, endDate: "2024-12-25" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "45671",
        comment: "Excellent quality leather wallet!",
        rating: 5,
        date: "2024-11-29",
      },
      {
        userId: "90734",
        comment: "Great size, but stitching could be better.",
        rating: 4,
        date: "2024-11-27",
      },
    ],
  },
  {
    id: "WS011",
    name: "Slip-On Ballet Flats",
    description:
      "Comfortable slip-on ballet flats with soft cushioning and anti-slip soles. Available in black and beige.",
    category: "Women's Shoes",
    price: 7999,
    currency: "NGN",
    brand: "ShoeWave",
    stock: 150,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 120 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      material: "Synthetic Leather",
      color: "Black",
      sizes: ["38", "39", "40", "41"],
    },
    tags: ["ballet flats", "women shoes", "casual"],
    seller: {
      name: "ShoeWorld",
      rating: 4.8,
      contact: "shoeworld@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-10" },
    shipping: { free: false, estimatedDelivery: "4-6 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "73862",
        comment: "Super comfortable and stylish.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "48306",
        comment: "Nice flats, but could be a little more durable.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "EA004",
    name: "Portable Power Bank 10000mAh",
    description:
      "Compact power bank with 10000mAh capacity, fast charging technology, and dual USB ports for multiple devices.",
    category: "Electronics Accessories",
    price: 5499,
    currency: "NGN",
    brand: "PowerX",
    stock: 200,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.5, reviews: 50 },
    specifications: { capacity: "10000mAh", color: "Black", weight: "250g" },
    tags: ["power bank", "electronics", "portable charger"],
    seller: {
      name: "GadgetTech",
      rating: 4.7,
      contact: "gadgettech@example.com",
    },
    discount: { percentage: 5, endDate: "2024-12-15" },
    shipping: { free: false, estimatedDelivery: "3-5 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "96327",
        comment: "Great charging speed, and reliable.",
        rating: 5,
        date: "2024-11-30",
      },
      {
        userId: "18456",
        comment: "It works well, but could be a little lighter.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "CLOTH002",
    name: "Casual T-Shirt for Men",
    description:
      "Soft, breathable cotton t-shirt available in various colors. Perfect for casual wear.",
    category: "Clothing",
    price: 2999,
    currency: "NGN",
    brand: "StyleFit",
    stock: 120,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.4, reviews: 85 },
    specifications: {
      material: "Cotton",
      color: "Blue",
      sizes: ["M", "L", "XL", "XXL"],
    },
    tags: ["t-shirt", "casual wear", "men clothing"],
    seller: { name: "FitWear", rating: 4.6, contact: "fitwear@example.com" },
    discount: { percentage: 8, endDate: "2024-12-30" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "28701",
        comment: "Comfortable, fits perfectly!",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "69324",
        comment: "Nice material but the color fades after washing.",
        rating: 3,
        date: "2024-11-29",
      },
    ],
  },
  {
    id: "MS012",
    name: "Leather Dress Shoes",
    description:
      "Elegant and durable leather dress shoes with cushioned insoles, perfect for formal events and office wear.",
    category: "Men's Shoes",
    price: 14999,
    currency: "NGN",
    brand: "GentleSteps",
    stock: 45,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.8, reviews: 130 },
    specifications: {
      material: "Genuine Leather",
      color: "Brown",
      sizes: ["40", "41", "42", "43"],
    },
    tags: ["dress shoes", "leather", "formal wear"],
    seller: {
      name: "GentleStyle",
      rating: 4.7,
      contact: "gentlestyle@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "29384",
        comment: "Perfect fit and very comfortable.",
        rating: 5,
        date: "2024-12-03",
      },
      {
        userId: "42839",
        comment: "Good quality but a bit expensive.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "KBC004",
    name: "Baby Onesie with Hood",
    description:
      "Soft cotton onesie for babies, featuring a cute hood and comfortable snap buttons for easy dressing.",
    category: "Kids & Baby Clothing",
    price: 4499,
    currency: "NGN",
    brand: "BabyCuddles",
    stock: 100,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.9, reviews: 75 },
    specifications: { material: "Cotton", color: "Pink", size: "0-6 months" },
    tags: ["onesie", "baby clothing", "comfortable"],
    seller: {
      name: "BabyClothing",
      rating: 5.0,
      contact: "babyclothing@example.com",
    },
    discount: { percentage: 12, endDate: "2024-12-20" },
    shipping: { free: true, estimatedDelivery: "3-5 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "47892",
        comment: "Very soft and comfortable for my baby.",
        rating: 5,
        date: "2024-12-02",
      },
      {
        userId: "23947",
        comment: "Cute design, but a little small for the size.",
        rating: 4,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "HA013",
    ujjn: "kndk",
    name: "accessories",
    name: "Smart Home Thermostat",
    description:
      "Wi-Fi enabled smart thermostat to control your home’s temperature remotely via an app for maximum comfort and energy savings.",
    category: "Household Accessories",
    price: 18999,
    currency: "NGN",
    brand: "HomeTech",
    stock: 30,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.3, reviews: 40 },
    specifications: { connectivity: "Wi-Fi", color: "White", weight: "500g" },
    tags: ["smart home", "thermostat", "energy saving"],
    seller: {
      name: "SmartHomeStore",
      rating: 4.5,
      contact: "smarthomestore@example.com",
    },
    discount: { percentage: 8, endDate: "2024-12-10" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: true,
    wishlist: false,
    reviews: [
      {
        userId: "12895",
        comment: "Easy setup and works great!",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "35840",
        comment: "It takes time to learn how to adjust settings.",
        rating: 3,
        date: "2024-11-28",
      },
    ],
  },
  {
    id: "EA005",
    name: "Bluetooth Speaker",
    description:
      "Portable Bluetooth speaker with high-quality sound and a built-in microphone for hands-free calls. Available in various colors.",
    category: "Electronics Accessories",
    price: 7499,
    currency: "NGN",
    brand: "SoundBox",
    stock: 200,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.7, reviews: 90 },
    specifications: {
      connectivity: "Bluetooth",
      color: "Black",
      weight: "300g",
    },
    tags: ["speaker", "bluetooth", "audio"],
    seller: {
      name: "AudioPlus",
      rating: 4.6,
      contact: "audioplus@example.com",
    },
    discount: { percentage: 10, endDate: "2024-12-15" },
    shipping: { free: true, estimatedDelivery: "4-6 business days" },
    addedToCart: false,
    wishlist: true,
    reviews: [
      {
        userId: "64829",
        comment: "Great sound quality for the price.",
        rating: 5,
        date: "2024-12-01",
      },
      {
        userId: "92714",
        comment: "Good value but lacks bass.",
        rating: 4,
        date: "2024-11-30",
      },
    ],
  },
  {
    id: "WS013",
    name: "Comfort Slip-On Flats",
    description:
      "Stylish slip-on flats with cushioned footbeds for all-day comfort and a sleek, modern design.",
    category: "Women's Shoes",
    price: 6499,
    currency: "NGN",
    brand: "ChicSteps",
    stock: 80,
    images: [
      "https://www.course-api.com/images/store/product-6.jpeg",
      "https://www.course-api.com/images/store/extra-product-1.jpeg",
      "https://www.course-api.com/images/store/extra-product-2.jpeg",
      "https://www.course-api.com/images/store/extra-product-3.jpeg",
      "https://www.course-api.com/images/store/extra-product-4.jpeg",
    ],
    ratings: { average: 4.6, reviews: 110 },
    sizes: [
      {
        size: "40",
        stock: 10,
      },
      {
        size: "41",
        stock: 8,
      },
      {
        size: "42",
        stock: 6,
      },
      {
        size: "44",
        stock: 4,
      },
      {
        size: "45",
        stock: 10,
      },
    ],
    specifications: {
      material: "Synthetic Leather",
      color: "Black",
      sizes: ["37", "38", "39", "40"],
    },
    tags: ["slip-on", "flats", "comfortable shoes"],
    seller: { name: "ChicWear", rating: 4.8, contact: "chicwear@example.com" },
    discount: { percentage: 12, endDate: "2024-12-20" },
    shipping: { free: false, estimatedDelivery: "5-7 business days" },
    addedToCart: false,
    wishlist: false,
    reviews: [
      {
        userId: "28493",
        comment: "Super comfortable, love these flats!",
        rating: 5,
        date: "2024-12-03",
      },
      {
        userId: "45623",
        comment: "Good fit but the material could be better.",
        rating: 4,
        date: "2024-11-29",
      },
    ],
  },
];
